# Generated by Django 3.0.6 on 2020-09-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_auto_20200926_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
