# Generated by Django 3.0.5 on 2020-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
